clear all;
clc;
disp('To determine the economic generation by using Lambda Iteration Method');
Lambda=input('Set the lambda value nearer to the beta value: ');
Pd=input('Enter the system load: ');
a1=input('Enter Alpha-1 value: ');
b1=input('Enter Beta-1 value:');
c1=input('Enter Gamma-1 value: ');
a2=input('Enter Alpha-2 value: '); 
b2=input('Enter Beta-2 value: ');
c2=input('Enter Gamma-2 value: ');
a3=input('Enter Alpha-3 value: '); 
b3=input('Enter Beta-3 value:');
c3=input('Enter Gamma-3 value: '); 
P1=(Lambda-b1)/(2*c1);
P2=(Lambda-b2)/(2*c2);
P3=(Lambda-b3)/(2*c3);
Delp=Pd-(P1+P2+P3);
DelLambda=Delp/((1/(2*c1))+(1/(2*c2))+(1/(2*c3)));
lambda=Lambda+DelLambda;
P1=(lambda-b1)/(2*c1);
P2=(lambda-b2)/(2*c2);
P3=(lambda-b3)/(2*c3);
F1=c1*P1^2+b1*P1+a1;
F2=c2*P2^2+b2*P2+a2;
F3=c3*P3^2+b3*P3+a3;
TotalCost=F1+F2+F3;
disp(lambda);
disp(P1);
disp(P2);
disp(P3);
disp(F1);
disp(F2);
disp(F3);
disp(TotalCost);