clear all:
clc;
rac1=input('Enter the value of Related area capacity-1 in MW:');
cil1=input('Enter the value of change in load-1 in MW:');
D1=input('Enter the value of damping coefficient-1 in pu:');
r1=input('Enter the value of regulation-1 in pu:');
rac2=input('Enter the value of Related area capacity-2 in MW:');
cil2=input('Enter t he value of change in load-2 in MW:');
D2=input('Enter the value of damping coefficient-2 in pu:');
r2=input('Enter teh value of regulation-2 in pu:');
f0=input('Enter the value of frequency:');
B=input('Enter the common base value in MW:');
B1=(D1+(1/r1));
B2=(D2+(1/r2));
delpd1=cil1/rac1;
delpd2=cil2/rac2;
a12=(rac1/rac2);
delf=-((a12*delpd1)+delpd2)/(B2+(a12*B1));
Delf=delf*f0;
f=f0+Delf;
disp('changing frequency in HZ:');
disp(Delf);
disp('Steady state frequency(new) in HZ:');
disp(f);
